apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "data-transformation-pipelines.fullname" . }}-configmap
data:
  {{ range $key, $value := .Values.env }}
    {{ $key }}: {{ $value | quote  }}
  {{ end }}