services:
  timescaledb:
    image: timescale/timescaledb-ha:pg14-latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
    restart: always
volumes:
    timescaledb_data:
      driver: local