apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "device-healthiness-monitoring-service.fullname" . }}-ad-pipeline-configmap
data:
  {{ range $key, $value := .Values.pipeline.env }}
  {{ $key }}: {{ $value | quote }}
  {{ end }}