apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "device-data-service.fullname" . }}-configmap
data:
  {{ range $key, $value := .Values.env }}
    {{ $key }}: {{$value | quote }}
  {{ end }}