services:
  mqtt:
    image: eclipse-mosquitto:2.0.18
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./config:/mosquitto/config
      - mosquitto_data:/mosquitto/data
    restart: always
volumes:
  mosquitto_data:
    driver: local