name: Reusable Docker Build Job
on:
  workflow_call:
    inputs:
      dockerfile_path:
        description: 'Path to the Dockerfile to build'
        required: true
        default: 'Dockerfile'
      service_directory:
        description: 'Directory containing the service to build'
        required: true
        default: '.'
      docker_image_name:
        description: 'Name of the Docker image to build'
        required: true
        default: 'bench352/test'
      docker_image_tag:
        description: 'Tag of the Docker image to build'
        required: true
        default: 'latest'
    secrets:
      DOCKER_USERNAME:
        description: 'Docker Hub username'
        required: true
      DOCKER_PASSWORD:
        description: 'Docker Hub password'
        required: true
jobs:
  build-docker-image:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ${{ github.event.inputs.service_directory }}
    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v3
      with:
        push: true
        context: ${{ github.event.inputs.service_directory }}
        file: ${{ github.event.inputs.dockerfile_path }}
        tags: ${{ github.event.inputs.docker_image_name }}:${{ github.event.inputs.docker_image_tag }}