name: Build Docker Images for Microservices
on: push
job:
  build-ema-service:
    uses: bench352/cs4514fyp/.github/workflows/reusable-docker-build.yml@backup
    with:
      dockerfile_path: ./code/ema-service/Dockerfile
      service_directory: ./code/ema-service
      docker_image_name: bench352/cs4514-ema-service
      docker_image_tag: latest