name: Build Docker Images for Microservices
on:
  push:
    branches:
      - main
jobs:
  build-ema-service:
    uses: bench352/cs4514fyp/.github/workflows/reusable-docker-build.yml@main
    with:
      dockerfile_path: ./code/ema-service/Dockerfile
      service_directory: ./code/ema-service
      docker_image_name: bench352/cs4514-ema-service
      docker_image_tag: latest
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  build-data-transformation-pipelines:
    uses: bench352/cs4514fyp/.github/workflows/reusable-docker-build.yml@main
    with:
      dockerfile_path: ./code/data-transformation-pipelines/Dockerfile
      service_directory: ./code/data-transformation-pipelines
      docker_image_name: bench352/cs4514-data-transformation-pipelines
      docker_image_tag: latest
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  build-device-data-service:
    uses: bench352/cs4514fyp/.github/workflows/reusable-docker-build.yml@main
    with:
      dockerfile_path: ./code/device-data-service/Dockerfile
      service_directory: ./code/device-data-service
      docker_image_name: bench352/cs4514-device-data-service
      docker_image_tag: latest
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  build-iot-device-simulator:
    uses: bench352/cs4514fyp/.github/workflows/reusable-docker-build.yml@main
    with:
      dockerfile_path: ./code/iot-device-simulator/Dockerfile
      service_directory: ./code/iot-device-simulator
      docker_image_name: bench352/cs4514-iot-device-simulator
      docker_image_tag: latest
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  build-ad-pipeline:
    uses: bench352/cs4514fyp/.github/workflows/reusable-docker-build.yml@main
    with:
      dockerfile_path: ./code/device-healthiness-monitoring-service/ad-pipeline/Dockerfile
      service_directory: ./code/device-healthiness-monitoring-service/ad-pipeline
      docker_image_name: bench352/cs4514-ad-pipeline
      docker_image_tag: latest
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  build-device-healthiness-monitoring-service:
    uses: bench352/cs4514fyp/.github/workflows/reusable-docker-build.yml@main
    with:
      dockerfile_path: ./code/device-healthiness-monitoring-service/web-server/Dockerfile
      service_directory: ./code/device-healthiness-monitoring-service/web-server
      docker_image_name: bench352/cs4514-device-healthiness-monitoring-service
      docker_image_tag: latest
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  build-web-ui:
    defaults:
      run:
        working-directory: ./code/web-ui
    runs-on: ubuntu-22.04
    env:
      dockerfile_path: ./code/web-ui/Dockerfile
      service_directory: ./code/web-ui
      docker_image_name: bench352/cs4514-shms-web-ui
      docker_image_tag: latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm install
      - run: npm run build
      - name: Build and Push Docker Image With Version
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ${{ env.service_directory }}
          file: ${{ env.dockerfile_path }}
          tags: ${{ env.docker_image_name }}:${{ env.docker_image_tag }}