name: Build Docker Images for Microservices
on:
  push:
    branches:
      - main
jobs:
  build-ema-service:
    uses: bench352/cs4514fyp/.github/workflows/reusable-docker-build.yml@main
    with:
      dockerfile_path: ./code/ema-service/Dockerfile
      service_directory: ./code/ema-service
      docker_image_name: bench352/cs4514-ema-service
      docker_image_tag: latest
    secrets:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  build-data-transformation-pipelines:
    uses: bench352/cs4514fyp/.github/workflows/reusable-docker-build.yml@main
    with:
      dockerfile_path: ./code/data-transformation-pipelines/Dockerfile
      service_directory: ./code/data-transformation-pipelines
      docker_image_name: bench352/cs4514-data-transformation-pipelines
      docker_image_tag: latest
    secrets:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  build-device-data-service:
    uses: bench352/cs4514fyp/.github/workflows/reusable-docker-build.yml@main
    with:
      dockerfile_path: ./code/device-data-service/Dockerfile
      service_directory: ./code/device-data-service
      docker_image_name: bench352/cs4514-device-data-service
      docker_image_tag: latest
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  build-iot-device-simulator:
    uses: bench352/cs4514fyp/.github/workflows/reusable-docker-build.yml@main
    with:
      dockerfile_path: ./code/iot-device-simulator/Dockerfile
      service_directory: ./code/iot-device-simulator
      docker_image_name: bench352/cs4514-iot-device-simulator
      docker_image_tag: latest
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}